### ISSUE TITLE
$jsonApi must not be accessed before initialization

### ISSUE THREAD

**Issue by nikitasunrise** [laravel-json-api/encoder-neomerx#5]
**Typed property LaravelJsonApi\\Encoder\\Neomerx\\Document::$jsonApi must not be accessed before initialization**

The class code explicitly declares the variable as null, but does not set a default value like the closest fields.
```
/**
 * @var JsonApi|null
 */
private ?JsonApi $jsonApi;

/**
 * @var Links|null
 */
private ?Links $links = null;

/**
 * @var Hash|null
 */
private ?Hash $meta = null;
```

I get this error when I try to disable in my responses _top-level JSON:API member_ (jsonapi filed).
The class Document.php also implements the method `withoutJsonApi()`. Using which you could disable this field, but not used anywhere

**Comment by lindyhopchris** [comment]
Good spot! I'll get this fixed this weekend.

**Comment by lindyhopchris** [comment]
Sorry, forgot to do this at the weekend. Just tagged `3.1.1` with the fix.
